Entity refactor feature branch
CSC207-2022F-UofT/course-project-dating-app-team pull request #39
Opened 2022-11-22 08:13 UTC by Daiiii99

**This is a working-in-progress branch** opening a draft pr for visibility

Let's all use this branch as a feature branch and only merge it into main when it's working again.
To continue adding to this feature branch, do the following: 
1. checkout database-entity-refactor branch
2. create a new branch base on database-entity-refactor branch
3. after making changes, push the publish the new branch onto GitHub and use pull request to merge into database-entity-refactor branch
4. after everyone is done making their changes, we will merge database-entity-refactor into main
5. To avoid conflicts and headaches, DO NOT DIRECTLY PUSH INTO database-entity-refactor anymore, this applies to myself as well. If I want to make further adjustments, I will open a PR as well

2022-11-25 22:28 UTC, mugengliu commented
Does it work right now?

2022-11-29 20:06 UTC, MikeJiahaoXu requested changes
1, make sure all names in entity and database are using the correct java naming convention.
2, you can delete the methods that you think will not be used in entities.

2022-12-01 16:06 UTC, MikeJiahaoXu approved these changes

2022-12-02 01:20 UTC, Rannu0 approved these changes

2022-12-02 01:41 UTC, karrrie approved these changes

2022-12-02 01:49 UTC, merged